language: java
script: mvn test
jdk:
- openjdk7
branches:
  only:
  - develop
env:
  global:
  - secure: YWNyOCJ8MJ8L7Q38iM0bALv8c2+V++/msDlpGcROEpAzfHHfRcOkYbQAXhQUDFa8HIya0BqVbJ6Sh07fPWJz0I3HP6PgvTuQJzqrsljNdHJiSepNfrXFAX0ra6Gqa7JJ+BZdKF60N3hfIiUi/ZpVuunii9x9J1QC2OeICflVshs=
  - secure: Ta4ZzSKlSdsg3YEwKP0c6ldeTC/a2tTua4FD26bfUzeIz3W2Lx/9SfxepyqZE7KR7eey52cgvx+9Sj9CJeDTTmgnPlwYi3v+pjn0YNQ0ZfIaiAk/TlaUJ1tXWq3GRGHumvFR38i6E66eIFT9Gg4Z5HSeQm1DCvpAie7Snj1RyDM=
after_success:
- python travis-prepare-maven.py
- mvn deploy --settings ~/.m2/trasettings.xml